In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2, os

In [7]:
train = pd.read_pickle("../assets/train.pkl")
valid = pd.read_pickle("../assets/valid.pkl")

In [83]:
y_train = train['category'].values
y_valid = valid['category'].values

In [84]:
X_train = train['image_150x150x3'].values
print(X_train.shape)
print(X_train[0].shape)

(14034,)
(150, 150, 3)

In [90]:
X_train = X_train.reshape(X_train.shape[0], 150, 150, 3) # First image

ValueError: cannot reshape array of size 14034 into shape (14034,150,150,3)

In [94]:
#train.image_150x150x3[image][col][row][RGB].shape
train.image_150x150x3[:].shape

(14034,)

In [87]:
train.image_150x150x3.values

array([array([[[245, 247, 247],
        [245, 247, 247],
        [246, 248, 248],
        ...,
        [248, 248, 248],
        [245, 247, 247],
        [245, 247, 247]],

       [[244, 246, 246],
        [245, 247, 247],
        [245, 247, 247],
        ...,
        [248, 248, 248],
        [245, 247, 247],
        [245, 247, 247]],

       [[244, 246, 246],
        [244, 246, 246],
        [245, 247, 247],
        ...,
        [248, 248, 248],
        [245, 247, 247],
        [245, 247, 247]],

       ...,

       [[ 44,  46,  47],
        [ 59,  61,  62],
        [ 46,  48,  49],
        ...,
        [ 43,  46,  51],
        [ 37,  40,  45],
        [ 86,  89,  94]],

       [[ 74,  76,  77],
        [ 44,  46,  47],
        [ 40,  42,  43],
        ...,
        [ 14,  17,  22],
        [ 47,  50,  55],
        [ 31,  34,  39]],

       [[ 56,  58,  59],
        [ 52,  54,  55],
        [ 57,  59,  60],
        ...,
        [ 23,  26,  31],
        [ 43,  46,  51],
        [ 55,  58,  63]]], dtype=uint8),
       array([[[186, 121,  70],
        [185, 122,  71],
        [184, 121,  71],
        ...,
        [233, 223, 223],
        [231, 222, 219],
        [228, 219, 216]],

       [[186, 123,  73],
        [184, 123,  73],
        [183, 122,  72],
        ...,
        [241, 233, 233],
        [238, 231, 228],
        [236, 229, 226]],

       [[182, 123,  77],
        [181, 122,  76],
        [180, 121,  75],
        ...,
        [245, 240, 239],
        [243, 238, 235],
        [240, 235, 232]],

       ...,

       [[ 20,  36,  35],
        [ 32,  50,  49],
        [ 21,  42,  39],
        ...,
        [ 28,  41,  55],
        [ 33,  46,  62],
        [ 31,  46,  62]],

       [[  9,  23,  22],
        [ 24,  40,  39],
        [ 21,  42,  39],
        ...,
        [ 51,  67,  80],
        [ 41,  56,  72],
        [ 25,  41,  57]],

       [[ 46,  60,  59],
        [  0,  14,  13],
        [ 21,  42,  39],
        ...,
        [  1,  17,  30],
        [ 41,  57,  73],
        [ 42,  58,  74]]], dtype=uint8),
       array([[[247, 194, 131],
        [247, 194, 131],
        [245, 194, 131],
        ...,
        [237, 217, 162],
        [238, 217, 165],
        [239, 218, 166]],

       [[247, 194, 131],
        [245, 194, 131],
        [245, 194, 131],
        ...,
        [239, 218, 166],
        [240, 219, 168],
        [238, 217, 166]],

       [[244, 193, 130],
        [244, 193, 130],
        [244, 193, 131],
        ...,
        [240, 218, 170],
        [239, 219, 171],
        [238, 218, 170]],

       ...,

       [[163, 171, 171],
        [158, 168, 168],
        [157, 165, 165],
        ...,
        [ 46, 147, 125],
        [ 43, 144, 119],
        [ 46, 147, 122]],

       [[178, 187, 190],
        [187, 199, 201],
        [204, 213, 216],
        ...,
        [ 56, 156, 134],
        [ 56, 154, 130],
        [ 62, 160, 136]],

       [[239, 251, 253],
        [235, 247, 249],
        [231, 243, 245],
        ...,
        [ 57, 155, 133],
        [ 53, 149, 125],
        [ 57, 153, 129]]], dtype=uint8),
       ...,
       array([[[ 67,  60,  63],
        [121, 114, 117],
        [111, 100, 103],
        ...,
        [  0,   0,  11],
        [ 11,  14,  19],
        [  0,   3,   2]],

       [[ 96,  89,  92],
        [137, 130, 133],
        [106,  97, 100],
        ...,
        [  3,   5,  16],
        [  0,   3,   7],
        [  5,  10,   9]],

       [[128, 123, 125],
        [128, 121, 124],
        [138, 129, 132],
        ...,
        [  7,  10,  15],
        [  0,   0,   3],
        [ 18,  20,  21]],

       ...,

       [[ 89,  94,  93],
        [112, 117, 116],
        [130, 132, 132],
        ...,
        [131, 136, 135],
        [133, 138, 137],
        [135, 140, 139]],

       [[ 86,  92,  91],
        [114, 120, 119],
        [128, 133, 132],
        ...,
        [134, 139, 138],
        [127, 132, 131],
        [130, 135, 134]],

       [[ 84,  90,  89],
        [114, 120, 119],
        [125, 130, 129],
        ...,
        [148, 153, 152],
        [127, 132, 131],
        [137, 142, 141]]], dtype=uint8),
       array([[[103,  29,   0],
        [104,  30,   0],
        [103,  31,   0],
        ...,
        [ 93,  22,   0],
        [ 94,  22,   0],
        [ 95,  24,   0]],

       [[171,  88,  26],
        [170,  90,  27],
        [170,  90,  25],
        ...,
        [162,  87,  49],
        [164,  87,  48],
        [163,  87,  45]],

       [[176,  79,   5],
        [175,  80,   6],
        [174,  81,   6],
        ...,
        [156,  72,  24],
        [157,  72,  24],
        [157,  72,  22]],

       ...,

       [[ 16,  15,  17],
        [ 18,  17,  19],
        [ 20,  19,  21],
        ...,
        [ 39,  38,  42],
        [ 37,  36,  40],
        [ 34,  33,  37]],

       [[ 29,  28,  30],
        [ 28,  27,  29],
        [ 28,  27,  29],
        ...,
        [ 72,  68,  73],
        [ 52,  48,  53],
        [ 51,  47,  52]],

       [[  2,   1,   3],
        [  0,   0,   1],
        [  0,   0,   1],
        ...,
        [  7,   3,   8],
        [  3,   0,   4],
        [  2,   0,   3]]], dtype=uint8),
       array([[[119, 110,  97],
        [125, 116, 106],
        [212, 208, 203],
        ...,
        [184, 166, 159],
        [168, 149, 141],
        [112,  93,  85]],

       [[124, 114, 104],
        [127, 120, 111],
        [221, 216, 213],
        ...,
        [201, 181, 170],
        [162, 142, 131],
        [202, 182, 171]],

       [[123, 112, 108],
        [128, 119, 116],
        [233, 226, 229],
        ...,
        [193, 170, 154],
        [212, 186, 172],
        [188, 162, 150]],

       ...,

       [[ 55,  58,  62],
        [243, 248, 247],
        [174, 175, 171],
        ...,
        [117, 132, 141],
        [105, 117, 127],
        [ 84,  99, 108]],

       [[  2,   6,   7],
        [248, 253, 252],
        [144, 145, 141],
        ...,
        [ 67,  78,  82],
        [ 77,  86,  90],
        [ 70,  81,  85]],

       [[  0,   0,   1],
        [241, 246, 245],
        [184, 186, 180],
        ...,
        [ 91,  98, 101],
        [118, 125, 128],
        [137, 144, 147]]], dtype=uint8)], dtype=object)

In [9]:
valid

                                         image_150x150x3  category
20057  [[[174, 119, 92], [189, 140, 114], [166, 124, ...         0
20060  [[[222, 182, 110], [221, 181, 109], [220, 181,...         0
20061  [[[247, 233, 227], [247, 233, 227], [247, 233,...         0
20064  [[[238, 173, 145], [238, 173, 145], [238, 174,...         0
20073  [[[145, 81, 40], [145, 81, 40], [145, 81, 40],...         0
...                                                  ...       ...
24292  [[[96, 110, 116], [108, 116, 116], [87, 81, 74...         5
24300  [[[57, 49, 49], [65, 57, 57], [73, 65, 65], [8...         5
24315  [[[158, 80, 13], [158, 80, 13], [158, 80, 13],...         5
24317  [[[187, 156, 125], [189, 158, 127], [188, 159,...         5
24332  [[[0, 0, 3], [20, 25, 28], [13, 17, 22], [10, ...         5

[3000 rows x 2 columns]

In [15]:
train_indices = list(train.index)
valid_indices = list(valid.index)
print(len(train_indices))
print(len(valid_indices))

14034
3000

In [25]:
X_train = train['image_150x150x3']
X_train[1].shape

(150, 150, 3)

In [18]:
train.image_150x150x3[0].shape

(150, 150, 3)

In [ ]:
# Make sure each value is a float. (Otherwise, we get an error.)
X_train = train.image_150x150x3.astype('float32')
X_test = X_test.astype('float32')
# 32 bit floating is a 24 bit recording with 8 extra bits for volume

# The current range of X_train and X_test is 0 to 255.
# The code below is equivalent to X_train = X_train / 255.
# This scales each value to be between 0 and 1.
X_train /= 255
X_test /= 255